analytics: {}
color:
  brandColors:
    - '#fefe00'
    - '#11110f'
    - '#ffffff'
    - '#787808'
    - '#b3b003'
  brandStrength: 0.5
  lightness: 0.6805669681634754
  rhythmicContrast: 0.11837757448665798
  saturation: 0.8514754353091121
cta: {}
layout_spectrum: 0.74657
name: Capital Region Real Estate
opengraph: {}
purpose: []
typography_spectrum: 0.75254
