name: Capital Region Real Estate
favicon: null
layout_spectrum: 0.9493966826703399
typography_spectrum: 0.32747907121665776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.10342206642962992
  lightness: 0.6805669681634754
  saturation: 0.8514754353091121
  rhythmicContrast: 0.11837757448665798
purpose: []
