name: Real Estate Sale
favicon: null
layout_spectrum: 0.98967
typography_spectrum: 0.75254
title: >-
  Irvin Ackerman:  Associate Real Estate Broker at Weichert Realtors Expert
  Advisors 
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefe00'
    - '#11110f'
    - '#ffffff'
    - '#787808'
    - '#b3b003'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
