name: Capital Region Real Estate
favicon: null
layout_spectrum: 0.74657
typography_spectrum: 0.75254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefe00'
    - '#11110f'
    - '#ffffff'
    - '#787808'
    - '#b3b003'
  brandStrength: 0.5
  lightness: 0.6805669681634754
  saturation: 0.8514754353091121
  rhythmicContrast: 0.11837757448665798
purpose: []
